import React, {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useState,
} from "react";

export type Language = "en" | "hi" | "mr";

const translations = {
  en: {
    // ===== Navigation =====
    dashboard: "Dashboard",
    addUser: "Add User",
    calculator: "Calculator",
    reminders: "Reminders",
    settings: "Settings",
    logout: "Logout",
    search: "Search borrowers, phone, email...",
    backToDashboard: "Back to dashboard",
    signedInAs: "Signed in as",
    trackOverview: "Track your lending performance at a glance.",
    risk: "Risk",
    reminderSetForDay: "Reminder is set for day {day} of every month.",
    calculateSubtitle: "Calculate loan interest and totals across any time period.",
    returnDateOptional: "Return Date (Optional)",
    quickAdjustInterest: "Quick Adjust Interest Rate",

    // ===== Settings – general =====
    preferences: "Preferences",
    settingsTitle: "Settings",
    settingsSubtitle: "Personalize your LendFlow workspace.",
    appearance: "Appearance",
    notifications: "Notifications",
    privacySecurity: "Privacy & Security",
    account: "Account",
    profile: "Profile",
    editProfile: "Edit profile",
    about: "About LendFlow",

    // ===== Language =====
    language: "Language",
    languageDescription: "Choose the language used across the app.",
    currentLanguage: "Current language",
    english: "English",
    hindi: "Hindi",
    marathi: "Marathi",

    // ===== Appearance =====
    darkMode: "Dark mode",
    darkModeDescription: "Use a darker color scheme across the app.",
    on: "On",
    off: "Off",
    theme: "Theme",
    themeDescription: "Choose how LendFlow looks on your device.",

    // ===== Notifications =====
    reminderPreferences: "Reminder preferences",
    reminderPreferencesDesc: "Manage when and how you're notified",
    pushNotifications: "Push notifications",
    pushNotificationsDesc: "Get alerts for due and overdue loans",
    reminderEmails: "Reminder emails",
    reminderEmailsDesc: "Receive email reminders before due dates",

    // ===== Privacy & Security =====
    changePassword: "Change password",
    changePasswordDesc: "Update your account password",
    privacyPolicy: "Privacy policy",
    termsOfService: "Terms of service",

    // ===== Common actions =====
    cancel: "Cancel",
    save: "Save",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    loading: "Loading...",
    noResults: "No results found",

    // ===== Dashboard =====
    overview: "Overview",
    overviewSubtitle: "Track your lending performance at a glance.",
    totalBorrowed: "Total Borrowed",
    totalReceived: "Total Received",
    activeUsers: "Active Users",
    totalInterest: "Total Interest",
    financialAnalytics: "Financial Analytics",
    financialAnalyticsSubtitle: "Overview of borrowings, receipts, and interest",
    borrowed: "Borrowed",
    received: "Received",
    interest: "Interest",
    remaining: "Remaining",
    collectionRate: "Collection Rate",
    activeBorrowers: "Active Borrowers",
    addNew: "Add New",
    noBorrowers: "No borrowers yet",
    addFirstBorrower: "Add your first borrower →",
    loadingBorrowers: "Loading borrowers...",

    // ===== User Details / Forms =====
    basicInfo: "Basic Information",
    loanDetails: "Loan Details",
    reminderSettings: "Reminder Settings",
    fullName: "Full Name",
    phone: "Phone Number",
    email: "Email Address",
    address: "Address",
    borrowedAmount: "Borrowed Amount",
    interestRate: "Interest Rate (%)",
    frequency: "Frequency",
    startDate: "Start Date",
    returnDate: "Return Date",
    periods: "Periods",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    enableReminder: "Enable Reminders",
    enableReminderDesc: "Get notified before the return date",
    reminderDay: "Reminder Day of Month",
    preview: "Live Preview",
    totalPayable: "Total Payable",
    principal: "Principal",
    duration: "Duration",
    rate: "Rate",
    valid: "Valid",
    fillToPreview: "Fill in the details to see a live preview.",

    // ===== Buttons =====
    addPayment: "Add Payment",
    addUserButton: "Add User",
    updateUser: "Save Changes",
    adding: "Adding...",
    updating: "Updating...",
    paymentAmount: "Payment amount",
    note: "Note",
    optional: "Optional",
    confirmPayment: "Confirm Payment",
    paymentHistory: "Payment History",
    noPayments: "No payments recorded yet",
    noPaymentsDesc: "Add the first payment to start tracking.",
    riskLow: "LOW",
    riskMedium: "MEDIUM",
    riskHigh: "HIGH",
    paid: "Paid",
    deleteUserConfirm: "Delete this user?",
    processing: "Processing...",
    deleting: "Deleting...",
    deleteUser: "Delete User",
    deleteBorrower: "Delete borrower?",
    deleteUserDescription: "This will permanently remove this borrower and their payment history.",
    paymentNote: "Note (Optional)",
    addPaymentNote: "Add a note about this payment",

    // ===== Reminders =====
    dueIn3Days: "Due in 3 Days",
    todaysReminders: "Today's Reminders",
    overdueLoans: "Overdue Loans",
    upcomingReturns: "Upcoming Return Dates",
    sendAllOverdue: "Send All Overdue",
    notifyAdmin: "Notify Admin",
    notifyBorrower: "Notify Borrower",
    whatsappAdmin: "WhatsApp Admin",
    viewDetails: "View Details",
    totalDue: "Total Due",
    returnDateLabel: "Return Date",
    allCaughtUp: "All caught up!",
    allCaughtUpDesc: "You have no pending reminders at the moment.",
    noRemindersInCategory: "No reminders in this category.",
    immediateAction: "Immediate action required",
    prepareCollection: "Prepare for collection",
    nextSevenDays: "Next 7 days",
    scheduledToday: "Scheduled for today",
    all: "All",
    today: "Today",
    dueSoon: "Due Soon",
    overdue: "Overdue",
    upcoming: "Upcoming",

    // ===== Login / Register =====
    welcomeBack: "Welcome back",
    signInSubtitle: "Sign in to access your LendFlow dashboard.",
    createAccount: "Create your account",
    createAccountSubtitle: "Get started with LendFlow in less than a minute.",
    emailAddress: "Email address",
    password: "Password",
    confirmPassword: "Confirm password",
    rememberMe: "Keep me signed in",
    forgotPassword: "Forgot?",
    signIn: "Sign in",
    signingIn: "Signing in...",
    register: "Create account",
    registering: "Creating account...",
    orContinueWith: "or continue with",
    continueWithGoogle: "Continue with Google",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    createOne: "Create one",
    securedWith: "Secured with 256-bit encryption",
    termsAgreePrefix: "By creating an account, you agree to our",
    terms: "Terms",
    and: "and",
    privacy: "Privacy Policy",
    passwordStrengthWeak: "Weak",
    passwordStrengthFair: "Fair",
    passwordStrengthGood: "Good",
    passwordStrengthStrong: "Strong",
    passwordHint: "Use 8+ characters with uppercase, numbers & symbols.",
    passwordsDoNotMatch: "Passwords do not match",

    // ===== Errors =====
    errorInvalidEmail: "Enter a valid email",
    errorPasswordShort: "Password too short",
    errorNameRequired: "Name is required",
    errorPasswordsDontMatch: "Passwords do not match",
    errorInvalidCredentials: "Invalid credentials",
    errorRegistrationFailed: "Registration failed",
    errorSomethingWrong: "Something went wrong",
    errorNoConnection: "No internet connection",
    nextPaymentPending: "Next payment pending",

  },

  hi: {
    // ===== Navigation =====
    dashboard: "डैशबोर्ड",
    addUser: "उधारकर्ता जोड़ें",
    calculator: "कैलकुलेटर",
    reminders: "रिमाइंडर",
    settings: "सेटिंग्स",
    logout: "लॉग आउट",
    search: "उधारकर्ता, फोन, ईमेल खोजें...",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    signedInAs: "इस रूप में साइन इन किया",
    trackOverview: "एक नज़र में अपने ऋण प्रदर्शन को ट्रैक करें।",
    risk: "जोखिम",
    reminderSetForDay: "हर महीने दिन {day} के लिए रिमाइंडर सेट है।",
    calculateSubtitle: "किसी भी अवधि के लिए ऋण ब्याज और कुल राशि की गणना करें।",
    returnDateOptional: "वापसी की तारीख (वैकल्पिक)",
    quickAdjustInterest: "ब्याज दर त्वरित समायोजन",

    // ===== Settings – general =====
    preferences: "प्राथमिकताएं",
    settingsTitle: "सेटिंग्स",
    settingsSubtitle: "अपने LendFlow कार्यक्षेत्र को अपनी पसंद के अनुसार बदलें।",
    appearance: "दिखावट",
    notifications: "सूचनाएं",
    privacySecurity: "गोपनीयता और सुरक्षा",
    account: "खाता",
    profile: "प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    about: "LendFlow के बारे में",

    // ===== Language =====
    language: "भाषा",
    languageDescription: "ऐप में उपयोग होने वाली भाषा चुनें।",
    currentLanguage: "वर्तमान भाषा",
    english: "अंग्रेज़ी",
    hindi: "हिंदी",
    marathi: "मराठी",

    // ===== Appearance =====
    darkMode: "डार्क मोड",
    darkModeDescription: "ऐप में गहरे रंगों का उपयोग करें।",
    on: "चालू",
    off: "बंद",
    theme: "थीम",
    themeDescription: "चुनें कि LendFlow आपके डिवाइस पर कैसा दिखे।",

    // ===== Notifications =====
    reminderPreferences: "रिमाइंडर प्राथमिकताएं",
    reminderPreferencesDesc: "प्रबंधित करें कि आपको कब और कैसे सूचित किया जाए",
    pushNotifications: "पुश सूचनाएं",
    pushNotificationsDesc: "देय और अतिदेय ऋणों के लिए अलर्ट प्राप्त करें",
    reminderEmails: "रिमाइंडर ईमेल",
    reminderEmailsDesc: "देय तिथि से पहले ईमेल रिमाइंडर प्राप्त करें",

    // ===== Privacy & Security =====
    changePassword: "पासवर्ड बदलें",
    changePasswordDesc: "अपने खाते का पासवर्ड अपडेट करें",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",

    // ===== Common actions =====
    cancel: "रद्द करें",
    save: "सहेजें",
    confirm: "पुष्टि करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    noResults: "कोई परिणाम नहीं मिला",

    // ===== Dashboard =====
    overview: "अवलोकन",
    overviewSubtitle: "एक नज़र में अपने ऋण प्रदर्शन को ट्रैक करें।",
    totalBorrowed: "कुल उधार लिया",
    totalReceived: "कुल प्राप्त",
    activeUsers: "सक्रिय उपयोगकर्ता",
    totalInterest: "कुल ब्याज",
    financialAnalytics: "वित्तीय विश्लेषण",
    financialAnalyticsSubtitle: "उधार, प्राप्तियों और ब्याज का अवलोकन",
    borrowed: "उधार लिया",
    received: "प्राप्त",
    interest: "ब्याज",
    remaining: "शेष राशि",
    collectionRate: "संग्रह दर",
    activeBorrowers: "सक्रिय उधारकर्ता",
    addNew: "नया जोड़ें",
    noBorrowers: "अभी तक कोई उधारकर्ता नहीं",
    addFirstBorrower: "अपना पहला उधारकर्ता जोड़ें →",
    loadingBorrowers: "उधारकर्ता लोड हो रहे हैं...",

    // ===== User Details / Forms =====
    basicInfo: "मूल जानकारी",
    loanDetails: "ऋण विवरण",
    reminderSettings: "रिमाइंडर सेटिंग्स",
    fullName: "पूरा नाम",
    phone: "फ़ोन नंबर",
    email: "ईमेल पता",
    address: "पता",
    borrowedAmount: "उधार राशि",
    interestRate: "ब्याज दर (%)",
    frequency: "आवृत्ति",
    startDate: "प्रारंभ तिथि",
    returnDate: "वापसी तिथि",
    periods: "अवधियाँ",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    enableReminder: "रिमाइंडर सक्षम करें",
    enableReminderDesc: "वापसी तिथि से पहले सूचित करें",
    reminderDay: "महीने का रिमाइंडर दिन",
    preview: "लाइव पूर्वावलोकन",
    totalPayable: "कुल देय",
    principal: "मूलधन",
    duration: "अवधि",
    rate: "दर",
    valid: "मान्य",
    fillToPreview: "लाइव पूर्वावलोकन के लिए विवरण भरें।",

    // ===== Buttons =====
    addPayment: "भुगतान जोड़ें",
    addUserButton: "उपयोगकर्ता जोड़ें",
    updateUser: "परिवर्तन सहेजें",
    adding: "जोड़ रहे हैं...",
    updating: "अपडेट हो रहा है...",
    paymentAmount: "भुगतान राशि",
    note: "नोट",
    optional: "वैकल्पिक",
    confirmPayment: "भुगतान की पुष्टि करें",
    paymentHistory: "भुगतान इतिहास",
    noPayments: "अभी तक कोई भुगतान दर्ज नहीं",
    noPaymentsDesc: "ट्रैकिंग शुरू करने के लिए पहला भुगतान जोड़ें।",
    nextPaymentPending: "अगला भुगतान लंबित",
    riskLow: "कम",
    riskMedium: "मध्यम",
    riskHigh: "उच्च",
    paid: "भुगतान किया",
    deleteUserConfirm: "इस उपयोगकर्ता को हटाएं?",
    processing: "प्रक्रिया जारी...",
    deleting: "हटाया जा रहा है...",
    deleteUser: "उपयोगकर्ता हटाएं",
    deleteBorrower: "उधारकर्ता हटाएं?",
    deleteUserDescription: "यह उधारकर्ता और उसका भुगतान इतिहास स्थायी रूप से हटा देगा।",
    paymentNote: "नोट (वैकल्पिक)",
    addPaymentNote: "इस भुगतान के बारे में नोट जोड़ें",

    // ===== Reminders =====
    dueIn3Days: "3 दिनों में देय",
    todaysReminders: "आज के रिमाइंडर",
    overdueLoans: "अतिदेय ऋण",
    upcomingReturns: "आगामी वापसी तिथियां",
    sendAllOverdue: "सभी अतिदेय भेजें",
    notifyAdmin: "व्यवस्थापक को सूचित करें",
    notifyBorrower: "उधारकर्ता को सूचित करें",
    whatsappAdmin: "WhatsApp व्यवस्थापक",
    viewDetails: "विवरण देखें",
    totalDue: "कुल देय",
    returnDateLabel: "वापसी तिथि",
    allCaughtUp: "सब पूरा हो गया!",
    allCaughtUpDesc: "इस समय आपके पास कोई लंबित रिमाइंडर नहीं है।",
    noRemindersInCategory: "इस श्रेणी में कोई रिमाइंडर नहीं।",
    immediateAction: "तत्काल कार्रवाई आवश्यक",
    prepareCollection: "संग्रह की तैयारी करें",
    nextSevenDays: "अगले 7 दिन",
    scheduledToday: "आज के लिए निर्धारित",
    all: "सभी",
    today: "आज",
    dueSoon: "जल्द देय",
    overdue: "अतिदेय",
    upcoming: "आगामी",

    // ===== Login / Register =====
    welcomeBack: "वापसी पर स्वागत है",
    signInSubtitle: "अपने LendFlow डैशबोर्ड तक पहुंचने के लिए साइन इन करें।",
    createAccount: "अपना खाता बनाएं",
    createAccountSubtitle: "एक मिनट से भी कम समय में LendFlow के साथ शुरुआत करें।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    rememberMe: "मुझे साइन इन रखें",
    forgotPassword: "भूल गए?",
    signIn: "साइन इन करें",
    signingIn: "साइन इन हो रहा है...",
    register: "खाता बनाएं",
    registering: "खाता बनाया जा रहा है...",
    orContinueWith: "या जारी रखें",
    continueWithGoogle: "Google के साथ जारी रखें",
    noAccount: "खाता नहीं है?",
    haveAccount: "पहले से खाता है?",
    createOne: "एक बनाएं",
    securedWith: "256-बिट एन्क्रिप्शन से सुरक्षित",
    termsAgreePrefix: "खाता बनाकर, आप हमारी शर्तों से सहमत हैं",
    terms: "शर्तें",
    and: "और",
    privacy: "गोपनीयता नीति",
    passwordStrengthWeak: "कमज़ोर",
    passwordStrengthFair: "ठीक",
    passwordStrengthGood: "अच्छा",
    passwordStrengthStrong: "मजबूत",
    passwordHint: "8+ अक्षर, अपरकेस, संख्याएं और प्रतीक उपयोग करें।",
    passwordsDoNotMatch: "पासवर्ड मेल नहीं खाते",

    // ===== Errors =====
    errorInvalidEmail: "मान्य ईमेल दर्ज करें",
    errorPasswordShort: "पासवर्ड बहुत छोटा है",
    errorNameRequired: "नाम आवश्यक है",
    errorPasswordsDontMatch: "पासवर्ड मेल नहीं खाते",
    errorInvalidCredentials: "अमान्य क्रेडेंशियल",
    errorRegistrationFailed: "पंजीकरण विफल",
    errorSomethingWrong: "कुछ गलत हो गया",
    errorNoConnection: "इंटरनेट कनेक्शन नहीं",
  },

  mr: {
    // ===== Navigation =====
    dashboard: "डॅशबोर्ड",
    addUser: "उधारकर्ता जोडा",
    calculator: "कॅल्क्युलेटर",
    reminders: "स्मरणपत्रे",
    settings: "सेटिंग्ज",
    logout: "लॉग आउट",
    search: "उधारकर्ता, फोन, ईमेल शोधा...",
    backToDashboard: "डॅशबोर्डवर परत जा",
    signedInAs: "या नावाने साइन इन केले",
    trackOverview: "एका दृष्टीक्षेपात तुमची कर्ज कामगिरी ट्रॅक करा.",
    risk: "जोखीम",
    reminderSetForDay: "दर महिन्याला {day} तारखेसाठी स्मरणपत्र सेट केले आहे.",
    calculateSubtitle: "कोणत्याही कालावधीसाठी कर्ज व्याज आणि एकूण रकमेची गणना करा.",
    returnDateOptional: "परतफेडीची तारीख (पर्यायी)",
    quickAdjustInterest: "व्याज दर जलद समायोजन",

    // ===== Settings – general =====
    preferences: "प्राधान्ये",
    settingsTitle: "सेटिंग्ज",
    settingsSubtitle: "तुमचे LendFlow कार्यक्षेत्र वैयक्तिकृत करा.",
    appearance: "दिसणे",
    notifications: "सूचना",
    privacySecurity: "गोपनीयता आणि सुरक्षा",
    account: "खाते",
    profile: "प्रोफाइल",
    editProfile: "प्रोफाइल संपादित करा",
    about: "LendFlow बद्दल",

    // ===== Language =====
    language: "भाषा",
    languageDescription: "अ‍ॅपसाठी वापरली जाणारी भाषा निवडा.",
    currentLanguage: "सध्याची भाषा",
    english: "इंग्रजी",
    hindi: "हिंदी",
    marathi: "मराठी",

    // ===== Appearance =====
    darkMode: "डार्क मोड",
    darkModeDescription: "अ‍ॅपमध्ये गडद रंगसंगती वापरा.",
    on: "चालू",
    off: "बंद",
    theme: "थीम",
    themeDescription: "LendFlow तुमच्या डिव्हाइसवर कसा दिसेल ते निवडा.",

    // ===== Notifications =====
    reminderPreferences: "स्मरणपत्र प्राधान्ये",
    reminderPreferencesDesc: "तुम्हाला कधी आणि कसे सूचित केले जावे ते व्यवस्थापित करा",
    pushNotifications: "पुश सूचना",
    pushNotificationsDesc: "देय आणि थकीत कर्जांसाठी सूचना मिळवा",
    reminderEmails: "स्मरणपत्र ईमेल",
    reminderEmailsDesc: "देय तारखेपूर्वी ईमेल स्मरणपत्रे मिळवा",

    // ===== Privacy & Security =====
    changePassword: "पासवर्ड बदला",
    changePasswordDesc: "तुमच्या खात्याचा पासवर्ड अपडेट करा",
    privacyPolicy: "गोपनीयता धोरण",
    termsOfService: "सेवा अटी",

    // ===== Common actions =====
    cancel: "रद्द करा",
    save: "जतन करा",
    confirm: "पुष्टी करा",
    delete: "हटवा",
    edit: "संपादित करा",
    close: "बंद करा",
    loading: "लोड होत आहे...",
    noResults: "कोणतेही परिणाम आढळले नाहीत",

    // ===== Dashboard =====
    overview: "आढावा",
    overviewSubtitle: "एका दृष्टीक्षेपात तुमची कर्ज कामगिरी ट्रॅक करा.",
    totalBorrowed: "एकूण उधार घेतले",
    totalReceived: "एकूण प्राप्त",
    activeUsers: "सक्रिय वापरकर्ते",
    totalInterest: "एकूण व्याज",
    financialAnalytics: "आर्थिक विश्लेषण",
    financialAnalyticsSubtitle: "उधार, पावत्या आणि व्याजाचा आढावा",
    borrowed: "उधार घेतले",
    received: "प्राप्त",
    interest: "व्याज",
    remaining: "शिल्लक रक्कम",
    collectionRate: "वसुली दर",
    activeBorrowers: "सक्रिय उधारकर्ते",
    addNew: "नवीन जोडा",
    noBorrowers: "अद्याप उधारकर्ते नाहीत",
    addFirstBorrower: "तुमचा पहिला उधारकर्ता जोडा →",
    loadingBorrowers: "उधारकर्ते लोड होत आहेत...",

    // ===== User Details / Forms =====
    basicInfo: "मूलभूत माहिती",
    loanDetails: "कर्ज तपशील",
    reminderSettings: "स्मरणपत्र सेटिंग्ज",
    fullName: "पूर्ण नाव",
    phone: "फोन नंबर",
    email: "ईमेल पत्ता",
    address: "पत्ता",
    borrowedAmount: "उधार रक्कम",
    interestRate: "व्याज दर (%)",
    frequency: "वारंवारता",
    startDate: "प्रारंभ तारीख",
    returnDate: "परतीची तारीख",
    periods: "कालावधी",
    daily: "दैनिक",
    weekly: "साप्ताहिक",
    monthly: "मासिक",
    yearly: "वार्षिक",
    enableReminder: "स्मरणपत्रे सक्षम करा",
    enableReminderDesc: "परतीच्या तारखेपूर्वी सूचित करा",
    reminderDay: "महिन्याचा स्मरणपत्र दिवस",
    preview: "थेट पूर्वावलोकन",
    totalPayable: "एकूण देय",
    principal: "मुद्दल",
    duration: "कालावधी",
    rate: "दर",
    valid: "वैध",
    fillToPreview: "थेट पूर्वावलोकनासाठी तपशील भरा.",

    // ===== Buttons =====
    addPayment: "पेमेंट जोडा",
    addUserButton: "वापरकर्ता जोडा",
    updateUser: "बदल जतन करा",
    adding: "जोडत आहे...",
    updating: "अपडेट होत आहे...",
    paymentAmount: "पेमेंट रक्कम",
    note: "टीप",
    optional: "ऐच्छिक",
    confirmPayment: "पेमेंटची पुष्टी करा",
    paymentHistory: "पेमेंट इतिहास",
    noPayments: "अद्याप कोणतेही पेमेंट नोंदवलेले नाही",
    noPaymentsDesc: "ट्रॅकिंग सुरू करण्यासाठी पहिले पेमेंट जोडा.",
    nextPaymentPending: "पुढील पेमेंट प्रलंबित",
    riskLow: "कमी",
    riskMedium: "मध्यम",
    riskHigh: "उच्च",
    paid: "भरले",
    deleteUserConfirm: "हा वापरकर्ता हटवायचा?",
    processing: "प्रक्रिया सुरू आहे...",
    deleting: "हटवत आहे...",
    deleteUser: "वापरकर्ता हटवा",
    deleteBorrower: "उधारकर्ता हटवायचा आहे का?",
    deleteUserDescription: "हा उधारकर्ता आणि त्याचा पेमेंट इतिहास कायमचा हटवला जाईल.",
    paymentNote: "नोट (पर्यायी)",
    addPaymentNote: "या पेमेंटसाठी नोट जोडा",

    // ===== Reminders =====
    dueIn3Days: "3 दिवसांत देय",
    todaysReminders: "आजची स्मरणपत्रे",
    overdueLoans: "थकीत कर्जे",
    upcomingReturns: "येणाऱ्या परतीच्या तारखा",
    sendAllOverdue: "सर्व थकीत पाठवा",
    notifyAdmin: "प्रशासकाला सूचित करा",
    notifyBorrower: "उधारकर्त्याला सूचित करा",
    whatsappAdmin: "WhatsApp प्रशासक",
    viewDetails: "तपशील पहा",
    totalDue: "एकूण देय",
    returnDateLabel: "परतीची तारीख",
    allCaughtUp: "सर्व पूर्ण झाले!",
    allCaughtUpDesc: "सध्या तुमच्याकडे कोणतीही प्रलंबित स्मरणपत्रे नाहीत.",
    noRemindersInCategory: "या श्रेणीत स्मरणपत्रे नाहीत.",
    immediateAction: "तातडीने कारवाई आवश्यक",
    prepareCollection: "वसुलीसाठी तयारी करा",
    nextSevenDays: "पुढील 7 दिवस",
    scheduledToday: "आजसाठी नियोजित",
    all: "सर्व",
    today: "आज",
    dueSoon: "लवकर देय",
    overdue: "थकीत",
    upcoming: "येणारे",

    // ===== Login / Register =====
    welcomeBack: "पुन्हा स्वागत आहे",
    signInSubtitle: "तुमच्या LendFlow डॅशबोर्डमध्ये प्रवेश करण्यासाठी साइन इन करा.",
    createAccount: "तुमचे खाते तयार करा",
    createAccountSubtitle: "एका मिनिटापेक्षा कमी वेळात LendFlow सह प्रारंभ करा.",
    emailAddress: "ईमेल पत्ता",
    password: "पासवर्ड",
    confirmPassword: "पासवर्डची पुष्टी करा",
    rememberMe: "मला साइन इन ठेवा",
    forgotPassword: "विसरलात?",
    signIn: "साइन इन करा",
    signingIn: "साइन इन होत आहे...",
    register: "खाते तयार करा",
    registering: "खाते तयार होत आहे...",
    orContinueWith: "किंवा सुरू ठेवा",
    continueWithGoogle: "Google सह सुरू ठेवा",
    noAccount: "खाते नाही?",
    haveAccount: "आधीच खाते आहे?",
    createOne: "एक तयार करा",
    securedWith: "256-बिट एन्क्रिप्शनसह सुरक्षित",
    termsAgreePrefix: "खाते तयार करून, तुम्ही आमच्या अटींशी सहमत आहात",
    terms: "अटी",
    and: "आणि",
    privacy: "गोपनीयता धोरण",
    passwordStrengthWeak: "कमकुवत",
    passwordStrengthFair: "ठीक",
    passwordStrengthGood: "चांगले",
    passwordStrengthStrong: "मजबूत",
    passwordHint: "8+ वर्ण, अप्परकेस, संख्या आणि चिन्हे वापरा.",
    passwordsDoNotMatch: "पासवर्ड जुळत नाहीत",

    // ===== Errors =====
    errorInvalidEmail: "वैध ईमेल प्रविष्ट करा",
    errorPasswordShort: "पासवर्ड खूप लहान आहे",
    errorNameRequired: "नाव आवश्यक आहे",
    errorPasswordsDontMatch: "पासवर्ड जुळत नाहीत",
    errorInvalidCredentials: "अवैध क्रेडेन्शियल्स",
    errorRegistrationFailed: "नोंदणी अयशस्वी",
    errorSomethingWrong: "काहीतरी चूक झाली",
    errorNoConnection: "इंटरनेट कनेक्शन नाही",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return saved === "hi" || saved === "mr" ? saved : "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
    // Notify native shell (Capacitor) if present
    if (typeof window !== "undefined" && (window as any).Capacitor) {
      try {
        (window as any).Capacitor.Plugins?.Device?.getLanguageCode?.();
      } catch {
        // Silently ignore — this is best-effort for native sync
      }
    }
  }, [language]);

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage);
  };

  const t = (key: TranslationKey) => translations[language][key];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};